name: Basic Issue
description: Use this when no other templates work for you
labels: []
projects: []
assignees:
  - gabekutner

body:
  - type: textarea
    id: what
    attributes:
      label: What's the problem?
      description: Description here ..