name: New Library Request
description: Use this when you want to propose adding a new library to package.json
labels: ["AddLibrary"]
projects: []
assignees:
  - gabekutner
body:
  - type: input
    id: library-name
    attributes:
      label: Name of library
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link to package
    validations:
      required: false

  - type: input
    id: problem-solved
    attributes:
      label: Problem solved by using this package
    validations:
      required: false

  - type: input
    id: stars
    attributes:
      label: Number of stars
    validations:
      required: false

  - type: input
    id: downloads
    attributes:
      label: Number of monthly downloads
    validations:
      required: false

  - type: input
    id: releases
    attributes:
      label: Number of releases in the last year
    validations:
      required: false

  - type: input
    id: activity
    attributes:
      label: Level of activity in the repo
    validations:
      required: false

  - type: input
    id: alternatives
    attributes:
      label: Alternatives
    validations:
      required: false

  - type: input
    id: concerns
    attributes:
      label: Are security concerns brought up and addressed in the library's repo?
    validations:
      required: false

  - type: input
    id: dependencies
    attributes:
      label: How many dependencies does this lib use that will be brought into our code?
    validations:
      required: false

  - type: input
    id: bundle-size
    attributes:
      label: What will the effect be on the bundle size of our code?
    validations:
      required: false
