name: Standard Issue
description: Use this when no other templates work for you
labels: []
projects: []
assignees:
  - gabekutner

body:
  - type: input
    id: title
    attributes:
      label: Title here ..

  - type: textarea
    id: what
    attributes:
      label: Description here ..

  